# Generated by Django 3.2.4 on 2021-08-15 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('alineamiento', models.CharField(choices=[('LB', 'Legal Bueno'), ('LN', 'Legal Neutral'), ('LM', 'Legal Malo'), ('NB', 'Neutral Bueno'), ('N', 'Neutral'), ('NM', 'Neutral Malo'), ('CB', 'Caótico Bueno'), ('CN', 'Caótico Neutral'), ('CM', 'Caótico Malo')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
