# Generated by Django 3.2.4 on 2021-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='alineamiento',
            field=models.CharField(choices=[('LB', 'Lb'), ('LN', 'Ln'), ('LM', 'Lm'), ('NB', 'Nb'), ('N', 'N'), ('NM', 'Nm'), ('CB', 'Cb'), ('CN', 'Cn'), ('CM', 'Cm')], max_length=2),
        ),
    ]
