# Generated by Django 3.2.4 on 2021-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='conjurosConocidos',
            field=models.ManyToManyField(to='main.Conjuro'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='esPublico',
            field=models.BooleanField(default=False, verbose_name='Es público'),
        ),
    ]
