# Generated by Django 3.2.4 on 2021-11-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211114_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='dote',
            name='creador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.perfil'),
        ),
    ]
