# Generated by Django 3.2.4 on 2021-08-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_personaje_alineamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificacionRaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonificacionRaza', models.TextField(verbose_name='Bonificación raza')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.TextField(verbose_name='Clase')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('dadosDeGolpe', models.IntegerField(default=6, verbose_name='Dados de golpe')),
                ('ataqueBase', models.TextField(null=True, verbose_name='Ataque base')),
                ('fortaleza', models.IntegerField(null=True, verbose_name='Fortaleza')),
                ('reflejos', models.IntegerField(null=True, verbose_name='Reflejos')),
                ('voluntad', models.IntegerField(null=True, verbose_name='Fortaleza')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Dote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Dote')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.TextField(verbose_name='Habilidad')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.TextField(verbose_name='Idioma')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Inmune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmune', models.TextField(verbose_name='Inmune')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='personaje',
            name='altura',
            field=models.TextField(null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='bmc',
            field=models.IntegerField(default=10, verbose_name='Bonus maniobra de combate'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='carga',
            field=models.TextField(null=True, verbose_name='Carga'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='carisma',
            field=models.IntegerField(default=10, verbose_name='Carisma'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='claseArmadura',
            field=models.IntegerField(default=10, verbose_name='Clase de armadura'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='constitucion',
            field=models.IntegerField(default=10, verbose_name='Constitución'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='desprevenido',
            field=models.IntegerField(default=10, verbose_name='Desprevenido'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='destreza',
            field=models.IntegerField(default=10, verbose_name='Destreza'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='dmc',
            field=models.IntegerField(default=10, verbose_name='Defensa maniobra de combate'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='fuerza',
            field=models.IntegerField(default=10, verbose_name='Fuerza'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='inteligencia',
            field=models.IntegerField(default=10, verbose_name='Inteligencia'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='peso',
            field=models.TextField(null=True, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='puntosDeGolpe',
            field=models.IntegerField(null=True, verbose_name='Puntos de golpe'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='resistenciaConjuros',
            field=models.IntegerField(null=True, verbose_name='Resistencia a Conjuros'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='resistenciaDano',
            field=models.IntegerField(null=True, verbose_name='Resistencia al daño'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='sabiduria',
            field=models.IntegerField(default=10, verbose_name='Sabiduría'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='toque',
            field=models.IntegerField(default=10, verbose_name='Toque'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='alineamiento',
            field=models.CharField(choices=[('LB', 'Legal Bueno'), ('LN', 'Legal Neutral'), ('LM', 'Legal Malo'), ('NB', 'Neutral Bueno'), ('N', 'Neutral'), ('NM', 'Neutral Malo'), ('CB', 'Caótico Bueno'), ('CN', 'Caótico Neutral'), ('CM', 'Caótico Malo')], max_length=2, null=True, verbose_name='alineamiento'),
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.TextField(verbose_name='Raza')),
                ('bonificacionRaza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bonificacionraza')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(null=True, verbose_name='Puntuación')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habilidad')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personaje')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PrerrequisitoDote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataqueBase', models.IntegerField(null=True, verbose_name='Ataque base')),
                ('clase', models.TextField(null=True, verbose_name='Clase')),
                ('nivel', models.IntegerField(null=True, verbose_name='Nivel')),
                ('fuerza', models.IntegerField(null=True, verbose_name='Fuerza')),
                ('destreza', models.IntegerField(null=True, verbose_name='Destreza')),
                ('constitucion', models.IntegerField(null=True, verbose_name='Constitucion')),
                ('inteligencia', models.IntegerField(null=True, verbose_name='Inteligencia')),
                ('sabiduria', models.IntegerField(null=True, verbose_name='Sabiduría')),
                ('carisma', models.IntegerField(null=True, verbose_name='Carisma')),
                ('dotes', models.ManyToManyField(to='main.Dote', verbose_name='Dotes')),
                ('puntuacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habilidad', verbose_name='Puntuación de habilidad')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='personaje',
            name='clase',
            field=models.ManyToManyField(to='main.Clase'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='idiomas',
            field=models.ManyToManyField(to='main.Idioma'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='inmune',
            field=models.ManyToManyField(to='main.Inmune'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.raza'),
        ),
    ]
