# Generated by Django 3.2.4 on 2021-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210815_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('escuela', models.TextField(verbose_name='Escuela')),
                ('tiempoDeLanzamiento', models.TextField(verbose_name='Tiempo de lanzamiento')),
                ('alcance', models.TextField(verbose_name='Alcance')),
                ('efecto', models.TextField(null=True, verbose_name='Efecto')),
                ('objetivo', models.TextField(null=True, verbose_name='Objetivo')),
                ('duracion', models.TextField(verbose_name='Duración')),
                ('tiroDeSalvacion', models.BooleanField(verbose_name='Tiro de salvación')),
                ('resistenciaConjuros', models.BooleanField(verbose_name='Resistencia a conjuros')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'ordering': ('nivel', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='HabilidadEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
            ],
            options={
                'ordering': ('nivel', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='NivelConjuroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PoderClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
            ],
            options={
                'ordering': ('nivel', 'nombre'),
            },
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ('clase',)},
        ),
        migrations.AlterModelOptions(
            name='dote',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ('habilidad',)},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'ordering': ('raza',)},
        ),
        migrations.AddField(
            model_name='clase',
            name='dotes',
            field=models.ManyToManyField(to='main.Dote'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='competente',
            field=models.ManyToManyField(to='main.Clase'),
        ),
        migrations.CreateModel(
            name='PrerrequisitoHabilidadEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(null=True, verbose_name='Nivel')),
                ('ataqueBase', models.IntegerField(null=True, verbose_name='Ataque base')),
                ('fuerza', models.IntegerField(null=True, verbose_name='Fuerza')),
                ('destreza', models.IntegerField(null=True, verbose_name='Destreza')),
                ('constitucion', models.IntegerField(null=True, verbose_name='Constitución')),
                ('inteligencia', models.IntegerField(null=True, verbose_name='Inteligencia')),
                ('sabiduria', models.IntegerField(null=True, verbose_name='Sabiduría')),
                ('carisma', models.IntegerField(null=True, verbose_name='Carisma')),
                ('poderes', models.ManyToManyField(to='main.PoderClase')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='conjuros',
            field=models.ManyToManyField(to='main.Conjuro'),
        ),
        migrations.AddField(
            model_name='clase',
            name='conjurosDiarios',
            field=models.ManyToManyField(to='main.NivelConjuroDiario'),
        ),
        migrations.AddField(
            model_name='clase',
            name='habilidadesEspeciales',
            field=models.ManyToManyField(to='main.HabilidadEspecial'),
        ),
        migrations.AddField(
            model_name='clase',
            name='poderes',
            field=models.ManyToManyField(to='main.PoderClase'),
        ),
    ]
