# Generated by Django 3.2.4 on 2021-11-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211114_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioEquipado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetos', models.ManyToManyField(to='main.Objeto')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioNoEquipado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetos', models.ManyToManyField(to='main.Objeto')),
            ],
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='inventario',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.AddField(
            model_name='personaje',
            name='inventario_equipado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inventarioequipado'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='inventario_no_equipado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inventarionoequipado'),
        ),
    ]
