# Generated by Django 3.2.4 on 2021-11-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211114_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='competencia',
            field=models.TextField(null=True, verbose_name='Competente con'),
        ),
    ]
