# Generated by Django 3.0.3 on 2022-02-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_habilidad_es_habilidad_companero_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='clases',
        ),
        migrations.AddField(
            model_name='personaje',
            name='clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Clase'),
        ),
    ]
