# Generated by Django 3.2.4 on 2021-11-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clase_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False, verbose_name='Está equipado')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventarionoequipado',
            name='objetos',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='propiedades',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='inventario_equipado',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='inventario_no_equipado',
        ),
        migrations.DeleteModel(
            name='InventarioEquipado',
        ),
        migrations.DeleteModel(
            name='InventarioNoEquipado',
        ),
        migrations.AddField(
            model_name='propiedadobjeto',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objeto'),
        ),
        migrations.AddField(
            model_name='propiedadobjeto',
            name='propiedades',
            field=models.ManyToManyField(to='main.Propiedad'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='propiedades_objeto',
            field=models.ManyToManyField(null=True, to='main.PropiedadObjeto'),
        ),
    ]
