# Generated by Django 3.2.4 on 2021-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211115_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='propiedades_objeto',
            field=models.ManyToManyField(to='main.PropiedadObjeto'),
        ),
    ]
