# Generated by Django 3.0.3 on 2022-04-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220204_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dote',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Perfil'),
        ),
    ]
