# Generated by Django 3.2.4 on 2021-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_personaje_propiedades_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='carisma',
            field=models.IntegerField(default=0, verbose_name='Carisma'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='constitucion',
            field=models.IntegerField(default=0, verbose_name='Constitución'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='destreza',
            field=models.IntegerField(default=0, verbose_name='Destreza'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='fuerza',
            field=models.IntegerField(default=0, verbose_name='Fuerza'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='inteligencia',
            field=models.IntegerField(default=0, verbose_name='Inteligencia'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='sabiduria',
            field=models.IntegerField(default=0, verbose_name='Sabiduría'),
        ),
    ]
