# Generated by Django 3.0.3 on 2022-04-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_companeroanimalpersonaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaneroAnimalPersonaje',
            fields=[
                ('companeroanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CompaneroAnimal')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('dotes', models.ManyToManyField(to='main.Dote')),
                ('personaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companero_animal_personaje', to='main.Personaje')),
                ('puntuacion_habilidad', models.ManyToManyField(to='main.PuntuacionHabilidad')),
                ('trucos', models.ManyToManyField(to='main.Truco')),
            ],
            options={
                'ordering': ('nombre',),
            },
            bases=('main.companeroanimal',),
        ),
    ]
