# Generated by Django 3.2.4 on 2021-11-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211115_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raza',
            old_name='bonificacion_raza',
            new_name='bonificaciones_raza',
        ),
    ]
