# Generated by Django 3.2.4 on 2021-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211115_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='objetos',
        ),
        migrations.AddField(
            model_name='personaje',
            name='poderes_conocidos',
            field=models.ManyToManyField(to='main.Poder'),
        ),
    ]
