# Generated by Django 3.2.4 on 2021-11-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211116_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companeroanimal',
            options={'ordering': ('tipo',)},
        ),
        migrations.RemoveField(
            model_name='companeroanimal',
            name='dotes',
        ),
        migrations.RemoveField(
            model_name='companeroanimal',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='companeroanimal',
            name='puntuacion_habilidad',
        ),
        migrations.RemoveField(
            model_name='companeroanimal',
            name='trucos',
        ),
        migrations.AddField(
            model_name='companeroanimal',
            name='tipo',
            field=models.TextField(null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='companero_animal',
            field=models.ManyToManyField(to='main.CompaneroAnimal'),
        ),
        migrations.CreateModel(
            name='CompaneroAnimalPersonaje',
            fields=[
                ('companeroanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.companeroanimal')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('dotes', models.ManyToManyField(to='main.Dote')),
                ('puntuacion_habilidad', models.ManyToManyField(to='main.PuntuacionHabilidadCA')),
                ('trucos', models.ManyToManyField(to='main.Truco')),
            ],
            bases=('main.companeroanimal',),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='companero_animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companeroanimalpersonaje'),
        ),
    ]
