# Generated by Django 3.2.4 on 2021-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211116_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truco',
            name='cd',
            field=models.TextField(verbose_name='CD'),
        ),
    ]
