# Generated by Django 3.2.4 on 2021-11-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_truco_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especial',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='especial',
            name='es_especial_companero_animal',
            field=models.BooleanField(default=False, verbose_name='Es especial de compañero animal'),
        ),
    ]
