# Generated by Django 3.2.4 on 2021-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211116_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadConjuroConocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
            ],
            options={
                'ordering': ('nivel',),
            },
        ),
        migrations.AlterModelOptions(
            name='nivelconjurodiario',
            options={'ordering': ('nivel',)},
        ),
        migrations.AddField(
            model_name='nivelconjurodiario',
            name='nivel',
            field=models.IntegerField(null=True, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='clase',
            name='cantidad_conjuros_conocidos',
            field=models.ManyToManyField(to='main.CantidadConjuroConocido'),
        ),
    ]
