# Generated by Django 3.2.4 on 2021-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211116_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='puntos_de_habilidad_por_nivel',
            field=models.TextField(null=True, verbose_name='Puntos de habilidad por nivel'),
        ),
    ]
