# Generated by Django 3.2.4 on 2021-11-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_clase_puntos_de_habilidad_por_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='especial',
            name='clase_perteneciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clase'),
        ),
    ]
