# Generated by Django 3.2.4 on 2021-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_especial_clase_perteneciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='ataque_base',
            field=models.TextField(null=True, verbose_name='Ataque base'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='dados_de_golpe',
            field=models.IntegerField(default=6, null=True, verbose_name='Dados de golpe'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fortaleza',
            field=models.IntegerField(null=True, verbose_name='Fortaleza'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nivel',
            field=models.IntegerField(default=1, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='reflejos',
            field=models.IntegerField(null=True, verbose_name='Reflejos'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='voluntad',
            field=models.IntegerField(null=True, verbose_name='Fortaleza'),
        ),
    ]
