# Generated by Django 3.2.4 on 2021-11-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211123_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poder',
            name='ataque_base',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='carisma',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='constitucion',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='destreza',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='fuerza',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='inteligencia',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='sabiduria',
        ),
        migrations.AlterField(
            model_name='poder',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nivel'),
        ),
        migrations.CreateModel(
            name='Linaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('linaje_arcano', models.TextField(verbose_name='Linaje arcano')),
                ('conjuros', models.ManyToManyField(to='main.Conjuro')),
                ('dotes', models.ManyToManyField(to='main.Dote')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habilidad')),
                ('poderes', models.ManyToManyField(to='main.Poder')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='linaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.linaje'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='linaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.linaje'),
        ),
    ]
