# Generated by Django 3.2.4 on 2021-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211125_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuro',
            name='clase',
            field=models.ManyToManyField(to='main.Clase'),
        ),
    ]
