# Generated by Django 3.2.4 on 2021-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_dote_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dote',
            name='tipo',
            field=models.CharField(choices=[('General', 'General'), ('Combate', 'Combate'), ('Metamágica', 'Metamagica')], max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
