# Generated by Django 3.2.4 on 2021-11-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211129_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dote',
            name='prerrequisito_raza',
        ),
        migrations.AddField(
            model_name='dote',
            name='prerrequisito_raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.raza'),
        ),
    ]
