# Generated by Django 3.2.4 on 2021-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20211129_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='es_propiedad_arma',
            field=models.BooleanField(default=False, verbose_name='Es propiedad de arma'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='es_propiedad_armadura',
            field=models.BooleanField(default=False, verbose_name='Es propiedad de armadura'),
        ),
    ]
