# Generated by Django 3.2.4 on 2021-11-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211130_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='prerrequisito_propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.propiedad'),
        ),
    ]
