# Generated by Django 3.2.4 on 2021-11-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_propiedad_prerrequisito_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='peso',
            field=models.FloatField(null=True, verbose_name='Peso'),
        ),
    ]
