# Generated by Django 3.2.4 on 2021-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_objeto_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio'),
        ),
    ]
