# Generated by Django 3.2.4 on 2021-11-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_objeto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='peso',
            field=models.FloatField(default=0.0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio'),
        ),
    ]
