# Generated by Django 3.2.4 on 2021-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20211130_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armadura',
            name='fallo_conj_arc',
            field=models.TextField(verbose_name='Fallo conjuro arcano'),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='penaliz_arm',
            field=models.TextField(verbose_name='Penalizador armadura'),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='velocidad_6m',
            field=models.TextField(verbose_name='Velocidad 6m'),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='velocidad_9m',
            field=models.TextField(verbose_name='Velocidad 9m'),
        ),
    ]
