# Generated by Django 3.0.3 on 2021-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211207_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armadura',
            name='bonif_max_des',
            field=models.IntegerField(null=True, verbose_name='Bonificación máximo destreza'),
        ),
    ]
