# Generated by Django 3.0.3 on 2021-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20211207_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='companeroanimal',
            name='numero_dotes',
            field=models.IntegerField(null=True, verbose_name='Número de dotes'),
        ),
        migrations.AddField(
            model_name='companeroanimal',
            name='numero_trucos',
            field=models.IntegerField(null=True, verbose_name='Número de trucos'),
        ),
        migrations.AddField(
            model_name='companeroanimal',
            name='puntos_habilidad',
            field=models.IntegerField(null=True, verbose_name='Puntos de habilidad'),
        ),
    ]
