# Generated by Django 3.0.3 on 2021-12-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20211207_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='companeroanimal',
            name='companero_animal_cambio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CompaneroAnimal'),
        ),
        migrations.AddField(
            model_name='companeroanimal',
            name='nivel_cambio',
            field=models.IntegerField(null=True, verbose_name='Nivel de cambio'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='carisma',
            field=models.IntegerField(default=0, verbose_name='Carisma'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='constitucion',
            field=models.IntegerField(default=0, verbose_name='Constitución'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='destreza',
            field=models.IntegerField(default=0, verbose_name='Destreza'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='fuerza',
            field=models.IntegerField(default=0, verbose_name='Fuerza'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='inteligencia',
            field=models.IntegerField(default=0, verbose_name='Inteligencia'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='sabiduria',
            field=models.IntegerField(default=0, verbose_name='Sabiduría'),
        ),
    ]
