# Generated by Django 3.0.3 on 2021-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20211207_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companeroanimal',
            name='nivel',
            field=models.IntegerField(null=True, verbose_name='Nivel'),
        ),
    ]
