# Generated by Django 3.0.3 on 2021-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211207_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companeroanimal',
            name='dados_de_golpe',
            field=models.IntegerField(null=True, verbose_name='Dados de golpe'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='puntos_de_golpe',
            field=models.IntegerField(null=True, verbose_name='Puntos de golpe'),
        ),
    ]
