# Generated by Django 3.0.3 on 2021-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20211207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companeroanimal',
            name='ataque_base',
            field=models.IntegerField(null=True, verbose_name='Ataque base'),
        ),
    ]
