# Generated by Django 3.0.3 on 2021-12-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20211207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companeroanimal',
            name='fortaleza',
            field=models.IntegerField(null=True, verbose_name='Fortaleza'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='reflejos',
            field=models.IntegerField(null=True, verbose_name='Reflejos'),
        ),
        migrations.AlterField(
            model_name='companeroanimal',
            name='voluntad',
            field=models.IntegerField(null=True, verbose_name='Voluntad'),
        ),
    ]
