# Generated by Django 3.0.3 on 2021-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20211207_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='companeroanimal',
            name='es_familiar',
            field=models.BooleanField(default=False, verbose_name='Es familiar'),
        ),
    ]
