# Generated by Django 3.0.3 on 2021-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_companeroanimal_es_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companeroanimal',
            name='ca',
            field=models.IntegerField(default=0, verbose_name='Clase de armadura'),
        ),
    ]
