# Generated by Django 3.0.3 on 2021-12-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20211208_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='habilidad',
            new_name='habilidades',
        ),
    ]
