# Generated by Django 3.0.3 on 2021-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20211208_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='dinero',
            field=models.FloatField(default=0.0, verbose_name='Dinero'),
        ),
    ]
