# Generated by Django 3.0.3 on 2021-12-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_personaje_dinero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='puntos_de_habilidad_por_nivel',
            field=models.IntegerField(null=True, verbose_name='Puntos de habilidad'),
        ),
    ]
