# Generated by Django 3.0.3 on 2021-12-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20211208_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='conjuros',
            field=models.ManyToManyField(to='main.Conjuro'),
        ),
    ]
