# Generated by Django 3.0.3 on 2021-12-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_clase_conjuros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='linaje',
        ),
        migrations.AddField(
            model_name='clase',
            name='linajes',
            field=models.ManyToManyField(to='main.Linaje'),
        ),
    ]
