# Generated by Django 3.0.3 on 2021-12-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20211209_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacionhabilidadca',
            name='habilidad',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='inmune',
        ),
        migrations.AddField(
            model_name='personaje',
            name='iniciativa',
            field=models.IntegerField(default=0, verbose_name='Iniciativa'),
        ),
        migrations.AlterField(
            model_name='companeroanimalpersonaje',
            name='puntuacion_habilidad',
            field=models.ManyToManyField(to='main.PuntuacionHabilidad'),
        ),
        migrations.DeleteModel(
            name='Inmune',
        ),
        migrations.DeleteModel(
            name='PuntuacionHabilidadCA',
        ),
    ]
