# Generated by Django 3.0.3 on 2021-12-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20211212_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='iniciativa',
        ),
    ]
