# Generated by Django 3.0.3 on 2021-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_personaje_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='clase_armadura',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='desprevenido',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='toque',
        ),
        migrations.RemoveField(
            model_name='propiedadobjeto',
            name='equipado',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='equipado',
            field=models.BooleanField(default=False, verbose_name='Está equipado'),
        ),
    ]
