# Generated by Django 3.0.3 on 2021-12-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20211221_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='clase',
            new_name='clases',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='bmc',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='dmc',
        ),
        migrations.AddField(
            model_name='clase',
            name='ataque_base_int',
            field=models.IntegerField(default=0, verbose_name='Ataque base'),
        ),
    ]
