# Generated by Django 3.0.3 on 2021-12-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20211221_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjuro',
            name='clases',
        ),
    ]
