# Generated by Django 3.0.3 on 2022-01-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificacionRaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CantidadConjuroConocido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
            ],
            options={
                'ordering': ('nivel',),
            },
        ),
        migrations.CreateModel(
            name='CompaneroAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(null=True, verbose_name='Tipo')),
                ('nivel', models.IntegerField(null=True, verbose_name='Nivel')),
                ('dados_de_golpe', models.IntegerField(null=True, verbose_name='Dados de golpe')),
                ('puntos_de_golpe', models.IntegerField(null=True, verbose_name='Puntos de golpe')),
                ('tamano', models.TextField(verbose_name='Tamaño')),
                ('velocidad', models.TextField(verbose_name='Velocidad')),
                ('ca', models.IntegerField(default=0, verbose_name='Clase de armadura')),
                ('ataque_base', models.IntegerField(null=True, verbose_name='Ataque base')),
                ('ataque', models.TextField(verbose_name='Ataque')),
                ('fuerza', models.IntegerField(default=0, verbose_name='Fuerza')),
                ('destreza', models.IntegerField(default=0, verbose_name='Destreza')),
                ('constitucion', models.IntegerField(default=0, verbose_name='Constitución')),
                ('inteligencia', models.IntegerField(default=0, verbose_name='Inteligencia')),
                ('sabiduria', models.IntegerField(default=0, verbose_name='Sabiduría')),
                ('carisma', models.IntegerField(default=0, verbose_name='Carisma')),
                ('fortaleza', models.IntegerField(null=True, verbose_name='Fortaleza')),
                ('reflejos', models.IntegerField(null=True, verbose_name='Reflejos')),
                ('voluntad', models.IntegerField(null=True, verbose_name='Voluntad')),
                ('numero_dotes', models.IntegerField(null=True, verbose_name='Número de dotes')),
                ('puntos_habilidad', models.IntegerField(null=True, verbose_name='Puntos de habilidad')),
                ('numero_trucos', models.IntegerField(null=True, verbose_name='Número de trucos')),
                ('nivel_cambio', models.IntegerField(null=True, verbose_name='Nivel de cambio')),
                ('es_familiar', models.BooleanField(default=False, verbose_name='Es familiar')),
                ('companero_animal_cambio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CompaneroAnimal')),
            ],
            options={
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='Conjuro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('escuela', models.TextField(verbose_name='Escuela')),
                ('tiempo_de_lanzamiento', models.TextField(verbose_name='Tiempo de lanzamiento')),
                ('componentes', models.TextField(null=True, verbose_name='Componentes')),
                ('alcance', models.TextField(verbose_name='Alcance')),
                ('efecto', models.TextField(null=True, verbose_name='Efecto')),
                ('area', models.TextField(null=True, verbose_name='Área')),
                ('objetivo', models.TextField(null=True, verbose_name='Objetivo')),
                ('duracion', models.TextField(verbose_name='Duración')),
                ('tiro_de_salvacion', models.TextField(verbose_name='Tiro de salvación')),
                ('resistencia_conjuros', models.TextField(verbose_name='Resistencia a conjuros')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'ordering': ('nivel', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Dote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Dote')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('tipo', models.CharField(choices=[('General', 'General'), ('Combate', 'Combate'), ('Metamágica', 'Metamagica')], max_length=10, null=True, verbose_name='Tipo')),
                ('nivel', models.IntegerField(null=True, verbose_name='Nivel')),
                ('ataque_base', models.IntegerField(null=True, verbose_name='Ataque base')),
                ('fuerza', models.IntegerField(null=True, verbose_name='Fuerza')),
                ('destreza', models.IntegerField(null=True, verbose_name='Destreza')),
                ('constitucion', models.IntegerField(null=True, verbose_name='Constitución')),
                ('inteligencia', models.IntegerField(null=True, verbose_name='Inteligencia')),
                ('sabiduria', models.IntegerField(null=True, verbose_name='Sabiduría')),
                ('carisma', models.IntegerField(null=True, verbose_name='Carisma')),
                ('es_dote_companero_animal', models.BooleanField(default=False, verbose_name='Es dote de compañero animal')),
            ],
            options={
                'ordering': ('tipo', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Especial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('es_especial_companero_animal', models.BooleanField(default=False, verbose_name='Es especial de compañero animal')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.TextField(verbose_name='Habilidad')),
                ('caracteristica', models.TextField(null=True, verbose_name='Característica')),
            ],
            options={
                'ordering': ('habilidad',),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.TextField(verbose_name='Idioma')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='NivelConjuroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('nivel', models.IntegerField(null=True, verbose_name='Nivel')),
            ],
            options={
                'ordering': ('nivel',),
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.TextField(null=True, verbose_name='Clase')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('precio', models.FloatField(default=0.0, verbose_name='Precio')),
                ('peso', models.FloatField(default=0.0, verbose_name='Peso')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(verbose_name='Nickname')),
                ('es_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('coste', models.IntegerField(null=True, verbose_name='Coste')),
                ('coste_dinero', models.IntegerField(null=True, verbose_name='Coste dinero')),
                ('equipado', models.BooleanField(default=False, verbose_name='Está equipado')),
                ('es_propiedad_arma', models.BooleanField(default=False, verbose_name='Es propiedad de arma')),
                ('es_propiedad_armadura', models.BooleanField(default=False, verbose_name='Es propiedad de armadura')),
                ('prerrequisito_propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_propiedad', to='main.Propiedad')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Objeto')),
                ('dano_p', models.TextField(verbose_name='Daño P')),
                ('dano_m', models.TextField(verbose_name='Daño M')),
                ('critico', models.TextField(verbose_name='Crítico')),
                ('alcance', models.TextField(null=True, verbose_name='Alcance')),
                ('tipo', models.TextField(verbose_name='Tipo')),
                ('especial', models.TextField(verbose_name='Especial')),
            ],
            options={
                'ordering': ('nombre',),
            },
            bases=('main.objeto',),
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Objeto')),
                ('bonif_arm', models.IntegerField(verbose_name='Bonificación armadura')),
                ('bonif_max_des', models.IntegerField(null=True, verbose_name='Bonificación máximo destreza')),
                ('penaliz_arm', models.TextField(verbose_name='Penalizador armadura')),
                ('fallo_conj_arc', models.TextField(verbose_name='Fallo conjuro arcano')),
                ('velocidad_9m', models.TextField(verbose_name='Velocidad 9m')),
                ('velocidad_6m', models.TextField(verbose_name='Velocidad 6m')),
            ],
            options={
                'ordering': ('nombre',),
            },
            bases=('main.objeto',),
        ),
        migrations.CreateModel(
            name='CompaneroAnimalPersonaje',
            fields=[
                ('companeroanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CompaneroAnimal')),
                ('nombre', models.TextField(verbose_name='Nombre')),
            ],
            bases=('main.companeroanimal',),
        ),
        migrations.CreateModel(
            name='Truco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cd', models.TextField(verbose_name='CD')),
                ('prerrequisito_truco', models.ManyToManyField(related_name='pr_truco', to='main.Truco')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.TextField(verbose_name='Raza')),
                ('tamano', models.TextField(null=True, verbose_name='Tamaño')),
                ('velocidad', models.TextField(null=True, verbose_name='Velocidad')),
                ('fuerza', models.IntegerField(default=0, verbose_name='Fuerza')),
                ('destreza', models.IntegerField(default=0, verbose_name='Destreza')),
                ('constitucion', models.IntegerField(default=0, verbose_name='Constitución')),
                ('inteligencia', models.IntegerField(default=0, verbose_name='Inteligencia')),
                ('sabiduria', models.IntegerField(default=0, verbose_name='Sabiduría')),
                ('carisma', models.IntegerField(default=0, verbose_name='Carisma')),
                ('idiomas_conocidos', models.TextField(null=True, verbose_name='Idiomas conocidos')),
                ('bonificaciones_raza', models.ManyToManyField(to='main.BonificacionRaza')),
                ('idiomas_eleccion', models.ManyToManyField(to='main.Idioma')),
            ],
            options={
                'ordering': ('raza',),
            },
        ),
        migrations.CreateModel(
            name='PuntuacionHabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(null=True, verbose_name='Puntuación')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Habilidad')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PropiedadObjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Objeto')),
                ('propiedades', models.ManyToManyField(to='main.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('prerrequisito_poder', models.ManyToManyField(related_name='pr_poder', to='main.Poder')),
            ],
            options={
                'ordering': ('nivel', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Linaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('linaje_arcano', models.TextField(verbose_name='Linaje arcano')),
                ('conjuros', models.ManyToManyField(to='main.Conjuro')),
                ('dotes', models.ManyToManyField(to='main.Dote')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Habilidad')),
                ('poderes', models.ManyToManyField(to='main.Poder')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='dote',
            name='creador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Perfil'),
        ),
        migrations.AddField(
            model_name='dote',
            name='prerrequisito_dote',
            field=models.ManyToManyField(related_name='pr_dote', to='main.Dote'),
        ),
        migrations.AddField(
            model_name='dote',
            name='prerrequisito_raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Raza'),
        ),
        migrations.AddField(
            model_name='companeroanimal',
            name='especiales',
            field=models.ManyToManyField(to='main.Especial'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.TextField(verbose_name='Clase')),
                ('nivel', models.IntegerField(default=0, verbose_name='Nivel')),
                ('dados_de_golpe', models.IntegerField(default=6, null=True, verbose_name='Dados de golpe')),
                ('ataque_base', models.TextField(null=True, verbose_name='Ataque base')),
                ('ataque_base_int', models.IntegerField(default=0, verbose_name='Ataque base')),
                ('fortaleza', models.IntegerField(null=True, verbose_name='Fortaleza')),
                ('reflejos', models.IntegerField(null=True, verbose_name='Reflejos')),
                ('voluntad', models.IntegerField(null=True, verbose_name='Fortaleza')),
                ('competencia', models.TextField(null=True, verbose_name='Competente con')),
                ('rafaga_de_golpes', models.TextField(null=True, verbose_name='Ráfaga de golpes')),
                ('dano_desarmado', models.TextField(null=True, verbose_name='Daño desarmado')),
                ('bonificacion_ac', models.IntegerField(null=True, verbose_name='Bonificación AC')),
                ('movimiento_rapido', models.IntegerField(null=True, verbose_name='Movimiento rápido')),
                ('puntos_de_habilidad_por_nivel', models.IntegerField(null=True, verbose_name='Puntos de habilidad')),
                ('descripcion_dados_de_golpe', models.TextField(null=True, verbose_name='Dado de golpe')),
                ('descripcion_puntos_de_habilidad', models.TextField(null=True, verbose_name='Puntos de habilidad por nivel')),
                ('descripcion_habilidades', models.TextField(null=True, verbose_name='Competente con las habilidades')),
                ('cantidad_conjuros_conocidos', models.ManyToManyField(to='main.CantidadConjuroConocido')),
                ('companero_animal', models.ManyToManyField(to='main.CompaneroAnimal')),
                ('conjuros', models.ManyToManyField(to='main.Conjuro')),
                ('especiales', models.ManyToManyField(to='main.Especial')),
                ('habilidades', models.ManyToManyField(to='main.Habilidad')),
                ('linajes', models.ManyToManyField(to='main.Linaje')),
                ('nivel_conjuro_diario', models.ManyToManyField(to='main.NivelConjuroDiario')),
                ('poderes', models.ManyToManyField(to='main.Poder')),
            ],
            options={
                'ordering': ('clase',),
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('alineamiento', models.CharField(choices=[('LB', 'Legal Bueno'), ('LN', 'Legal Neutral'), ('LM', 'Legal Malo'), ('NB', 'Neutral Bueno'), ('N', 'Neutral'), ('NM', 'Neutral Malo'), ('CB', 'Caótico Bueno'), ('CN', 'Caótico Neutral'), ('CM', 'Caótico Malo')], max_length=2, null=True, verbose_name='alineamiento')),
                ('puntos_de_golpe', models.IntegerField(null=True, verbose_name='Puntos de golpe')),
                ('resistencia_dano', models.IntegerField(null=True, verbose_name='Resistencia al daño')),
                ('resistencia_conjuros', models.IntegerField(null=True, verbose_name='Resistencia a Conjuros')),
                ('fuerza', models.IntegerField(default=10, verbose_name='Fuerza')),
                ('destreza', models.IntegerField(default=10, verbose_name='Destreza')),
                ('constitucion', models.IntegerField(default=10, verbose_name='Constitución')),
                ('inteligencia', models.IntegerField(default=10, verbose_name='Inteligencia')),
                ('sabiduria', models.IntegerField(default=10, verbose_name='Sabiduría')),
                ('carisma', models.IntegerField(default=10, verbose_name='Carisma')),
                ('dinero', models.FloatField(default=0.0, verbose_name='Dinero')),
                ('es_publico', models.BooleanField(default=False, verbose_name='Es público')),
                ('clases', models.ManyToManyField(to='main.Clase')),
                ('conjuros_conocidos', models.ManyToManyField(to='main.Conjuro')),
                ('dotes', models.ManyToManyField(to='main.Dote')),
                ('idiomas', models.ManyToManyField(to='main.Idioma')),
                ('linaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Linaje')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Perfil')),
                ('poderes_conocidos', models.ManyToManyField(to='main.Poder')),
                ('propiedades_objeto', models.ManyToManyField(to='main.PropiedadObjeto')),
                ('puntuaciones_habilidad', models.ManyToManyField(to='main.PuntuacionHabilidad')),
                ('raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Raza')),
                ('companero_animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompaneroAnimalPersonaje')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='companeroanimalpersonaje',
            name='dotes',
            field=models.ManyToManyField(to='main.Dote'),
        ),
        migrations.AddField(
            model_name='companeroanimalpersonaje',
            name='puntuacion_habilidad',
            field=models.ManyToManyField(to='main.PuntuacionHabilidad'),
        ),
        migrations.AddField(
            model_name='companeroanimalpersonaje',
            name='trucos',
            field=models.ManyToManyField(to='main.Truco'),
        ),
    ]
