# Generated by Django 3.0.3 on 2022-06-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armadura',
            name='objeto_ptr',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='prerrequisito_propiedad',
        ),
        migrations.RemoveField(
            model_name='propiedadobjeto',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='propiedadobjeto',
            name='propiedades',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='propiedades_objeto',
        ),
        migrations.DeleteModel(
            name='Arma',
        ),
        migrations.DeleteModel(
            name='Armadura',
        ),
        migrations.DeleteModel(
            name='Objeto',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
        migrations.DeleteModel(
            name='PropiedadObjeto',
        ),
    ]
