# Generated by Django 3.0.3 on 2022-02-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220125_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='companero_animal',
        ),
        migrations.AddField(
            model_name='companeroanimalpersonaje',
            name='personaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Personaje'),
        ),
    ]
