# Generated by Django 3.0.3 on 2022-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220202_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='es_habilidad_companero_animal',
            field=models.BooleanField(default=False, verbose_name='Es habilidad de compañero animal'),
        ),
    ]
