# Generated by Django 3.0.3 on 2022-04-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220418_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompaneroAnimalPersonaje',
        ),
    ]
