# Generated by Django 3.0.3 on 2022-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_companeroanimalpersonaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='idiomas_iniciales',
            field=models.ManyToManyField(related_name='idiomas_iniciales', to='main.Idioma'),
        ),
    ]
