# Generated by Django 3.0.3 on 2022-05-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220517_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='imagen',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
