# Generated by Django 3.0.3 on 2022-05-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_raza_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='imagen_completa',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen completa'),
        ),
    ]
